### ISSUE TITLE
Status App: [BUG] Installer doesn't save Non standard login info

### ISSUE THREAD

**Issue by misilot** [gvsulib/library-Status#29]
The installer doesn't save non standard login info.

**Comment by jonbloom** [comment]
I believe it. I'll check on it when I'm back in the office.

On May 10, 2015, at 9:48 AM, Thomas Misilo <notifications@github.com> wrote:

The installer doesn't save non standard login info.

—
Reply to this email directly or view it on GitHub
<https://github.com/gvsulib/library-Status/issues/29>.

**Comment by mreidsma** [comment]
Related to https://github.com/gvsulib/library-Status/issues/31 and https://github.com/gvsulib/library-Status/issues/30. SQL queries are failing when running install.php, but there is nothing alerting the installer to that failure.

Adding code to catch errors.

**Comment by mreidsma** [comment]
Removed easy installer, and added it to the road map. It has too many problems to keep supporting, so I'll write a new version this year.
