### ISSUE TITLE
Status App: [BUG] Installer completes and then wants to begin installing again

### ISSUE THREAD

**Issue by misilot** [gvsulib/library-Status#31]
After completing the installer, it wants it returns to the installer page.

**Comment by mreidsma** [comment]
I am unable to confirm this. Installer worked fine for me. I'm suspecting that other systems are failing to actually install the database details. When I tested it using MAMP, it works fine.

Could you give me a bit more information on your system? For instance, what version of PHP are you running? Is it possible to test out some of the queries with MySQL? If you have phpMyAdmin I can set the script up to echo the queries to the console so you could verify how things are running.

**Comment by mreidsma** [comment]
Removed easy installer, and added it to the road map. It has too many problems to keep supporting, so I'll write a new version this year.
